### ISSUE TITLE
Npm package issue

### ISSUE THREAD

**Issue by david-mkhitaryan-dev** [ForkPoint/davos#66]
After package installation via npm install davos command, it seems that the package code is not complete
In index.js file
line 3 const Core = require('./src/main');
throwing error, because src folder doesn't exist

@k2kirov 

Regards

**Comment by Arrogar** [comment]
Thank you @david-mkhitaryan-dev , will have a look at it as soon as possible!

Regards

**Comment by Arrogar** [comment]
@david-mkhitaryan-dev , should be all good now!

**Comment by david-mkhitaryan-dev** [comment]
Hi @Arrogar it's fine now.
Thank you
