### ISSUE TITLE
Metadata merge issue on Windows

### ISSUE THREAD

**Issue by david-mkhitaryan-dev** [ForkPoint/davos#72]
I remarked an issue with merge command on Windows
on line https://github.com/ForkPoint/davos/blob/733b3d6ae7447bb96d584966864c7cf03136c5ef/src/tasks/meta.merge.js#L37

globby(pattern) result is empty because of backslashes in pattern
So I fixed it temporarily by doing the hereunder
pattern = pattern.replace(/\\/g, "/");

OS: Windows 10
Node: 12.17.0

Best Regards

**Comment by k2kirov** [comment]
This is now fixed in the latest version alpha.13
